$axure.loadCurrentPage({
  "url":"学生.html",
  "generationDate":new Date(1526387353937.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f615ae327e534cdf99b9e07504213278",
    "type":"Axure:Page",
    "name":"学生",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9d718c0ef0654c5195c6ea9577b8c05c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1424,
              "height":1000},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"633fa5751ec84d2da12fbc46d1b49b2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1424,
                  "height":1000},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生/u0.png"}},
{
          "id":"4453bc03957045cea69960242f85a80f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":140},
            "size":{
              "width":427,
              "height":618}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f880d9f4c8db49ceb90576d17145de3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":466,
                  "y":140},
                "size":{
                  "width":427,
                  "height":618}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"a4c4804187594c76acf94a59a6109d13",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":793,
              "y":800},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e3d044e9ad88479ea3aeec91d72078e9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":800},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c3c8d9fd480946b3bb6920831f0757a1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f3cf3e2d438547948d7a6e0e1763c730"},
{
          "id":"74a8d9ed16f5441ab9df89ac556c5e76",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":793,
              "y":91},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生成绩的副本",
                      "target":{
                        "targetType":"page",
                        "url":"学生成绩的副本.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"022660d9261d4d7e97fa3bd80531ae0d",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":490.000030517578,
              "y":570},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e5b41719d8446cba26ce873119778d1",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f5b4098e4cc47cc987686680339057d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b3352294a47949feb00593d10868d7f6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/学生/u14.png"}}]},
{
              "id":"19bd86d91cf14aafa43f3b0e323b8f8a",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"805060fbb9bb4e50b26f9266813039d2",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fc32211c9304abd94945b51e6d8bd6c",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"037177f7a1e7490d91a96abca77e2ec9",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 小组作业",
                                  "target":{
                                    "targetType":"page",
                                    "url":"小组作业_1.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/学生/u18.png"}},
{
                      "id":"2f4ec2614849475fa4fff5678e1f67d6",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":100,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1fd6a03f2b8a4a8483087c85b0ff8932",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":100,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 小组互评",
                                  "target":{
                                    "targetType":"page",
                                    "url":"小组互评.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/学生/u20.png"}}]}],
              "parentCellId":"9f5b4098e4cc47cc987686680339057d"}]}]}},
  "masters":{
    "f3cf3e2d438547948d7a6e0e1763c730":{
      "packageId":"f3cf3e2d438547948d7a6e0e1763c730",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1b7cf0c362fe419884bcd418cc8bffed",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":1424,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c85da2bdffb405fa016fa16193cac3c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":1424,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF333333}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u2.png"}},
{
            "id":"da34571498c04a1db7f4f0bd16c6af6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":570,
                "y":15},
              "size":{
                "width":197,
                "height":34}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed8de50b3709411397b9eef361942054",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":570,
                    "y":15},
                  "size":{
                    "width":197,
                    "height":34}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "9d718c0ef0654c5195c6ea9577b8c05c":{
      "scriptId":"u0"},
    "633fa5751ec84d2da12fbc46d1b49b2b":{
      "scriptId":"u1"},
    "4453bc03957045cea69960242f85a80f":{
      "scriptId":"u2"},
    "f880d9f4c8db49ceb90576d17145de3f":{
      "scriptId":"u3"},
    "a4c4804187594c76acf94a59a6109d13":{
      "scriptId":"u4"},
    "e3d044e9ad88479ea3aeec91d72078e9":{
      "scriptId":"u5"},
    "c3c8d9fd480946b3bb6920831f0757a1":{
      "scriptId":"u6",
      "1b7cf0c362fe419884bcd418cc8bffed":{
        "scriptId":"u7"},
      "8c85da2bdffb405fa016fa16193cac3c":{
        "scriptId":"u8"},
      "da34571498c04a1db7f4f0bd16c6af6a":{
        "scriptId":"u9"},
      "ed8de50b3709411397b9eef361942054":{
        "scriptId":"u10"}},
    "74a8d9ed16f5441ab9df89ac556c5e76":{
      "scriptId":"u11"},
    "022660d9261d4d7e97fa3bd80531ae0d":{
      "scriptId":"u12"},
    "6e5b41719d8446cba26ce873119778d1":{
      "scriptId":"u13"},
    "9f5b4098e4cc47cc987686680339057d":{
      "scriptId":"u14"},
    "b3352294a47949feb00593d10868d7f6":{
      "scriptId":"u15"},
    "19bd86d91cf14aafa43f3b0e323b8f8a":{
      "scriptId":"u16"},
    "805060fbb9bb4e50b26f9266813039d2":{
      "scriptId":"u17"},
    "6fc32211c9304abd94945b51e6d8bd6c":{
      "scriptId":"u18"},
    "037177f7a1e7490d91a96abca77e2ec9":{
      "scriptId":"u19"},
    "2f4ec2614849475fa4fff5678e1f67d6":{
      "scriptId":"u20"},
    "1fd6a03f2b8a4a8483087c85b0ff8932":{
      "scriptId":"u21"}}});