$axure.loadCurrentPage({
  "url":"学生成绩单查看.html",
  "generationDate":new Date(1526387347134.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3d189da235dd489b87d96091c5e43783",
    "type":"Axure:Page",
    "name":"学生成绩单查看",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ba5514fa6fd4e9aa0ad3ceabccf0bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1424,
              "height":1060},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"774d9b713e6b4a71b308d05cd22e3695",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1424,
                  "height":1060},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u0.png"}},
{
          "id":"609a071248584b45a8abdc6f36fc2955",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1424,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51e1e223b3304b76a66908e13492a007",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1424,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"2ae62487e7294aa0a0451a1f4d5dab43",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":457,
              "y":14},
            "size":{
              "width":393,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"522f4c59a7c745739d49df905e268917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":457,
                  "y":14},
                "size":{
                  "width":393,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f0481e0fd484c53876f04f1bf81c13f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":200},
            "size":{
              "width":200,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e669f49afe54cf9808a1d3233b0a8c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":200},
                "size":{
                  "width":200,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u6.png"}},
{
          "id":"77d36a649ba44b6cab54eac13d566115",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":200},
            "size":{
              "width":200,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"279958309f114e80bbbe84ce8a0898bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":200},
                "size":{
                  "width":200,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u6.png"}},
{
          "id":"c4093495d6b944b697261bbd75a43ef9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":200},
            "size":{
              "width":100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b60e441bcc4c499860b5c10ff057a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":200},
                "size":{
                  "width":100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u10.png"}},
{
          "id":"295a344eacb246a8b83a885c82b1c261",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":200},
            "size":{
              "width":140,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8d74efbfce34e6787b72d2ea004c8b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":200},
                "size":{
                  "width":140,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u12.png"}},
{
          "id":"a00f8f3fc4a14e88863235db92833eeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":200},
            "size":{
              "width":150,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bfa1b5404c341e8951577cabe174f94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":200},
                "size":{
                  "width":150,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u14.png"}},
{
          "id":"1a78535d4fca461d8948b6e867e50a78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":280},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66ee410c892e480ba9d8827f502b1385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":280},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u16.png"}},
{
          "id":"46d3b30a7e7c491fbf519172b1f20480",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":280},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93eabba5762241f2aad3206f9c0646db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":280},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u16.png"}},
{
          "id":"9551c7a87fdb460092a013e6dbab861f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":280},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b57837c969ae42ff87e6ed00534945be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":280},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u20.png"}},
{
          "id":"2906de3e09654027ac55093ccf0fe065",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":280},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9aa51ec44f64c3199d19c550f2aa1f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":280},
                "size":{
                  "width":140,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u22.png"}},
{
          "id":"6ab73b6ff37947168204b690e3028a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":280},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32556b3963a3459595556d77202ebd87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":280},
                "size":{
                  "width":150,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 小组作业",
                      "target":{
                        "targetType":"page",
                        "url":"小组作业.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/学生成绩单查看/u24.png"}},
{
          "id":"48d38ab494e248ceae3103440aeb9546",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":330},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a142f1722584d54a4cb5715c9b07c01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":330},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u16.png"}},
{
          "id":"ba9a4f9ca92d4fbc80eac41e118b17ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":330},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d40d42ade3e45b8b02987fafca59ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":330},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u16.png"}},
{
          "id":"bc4e82e00c62456fa27580c8efbb783e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":330},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"686ab31f3d7043ac9cc85df0f82bde06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":330},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u20.png"}},
{
          "id":"dd0dda3068b5441f9382f955ca83aed2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":330},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e30b9e3dd32042c2aa82d28f952ca4fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":330},
                "size":{
                  "width":140,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人作业",
                      "target":{
                        "targetType":"page",
                        "url":"个人作业.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/学生成绩单查看/u22.png"}},
{
          "id":"b91c0467d4a34e8ebc517db259c7a191",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":330},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be4604ee3b3746e2aa30fe46716ff589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":330},
                "size":{
                  "width":150,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u24.png"}},
{
          "id":"18a7421f3d05473781da06139f21544f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":380},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcc22299fe614f229837aea5ec8b3041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":380},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u16.png"}},
{
          "id":"0ab815427cdb4a45bbc12387f79fef3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":380},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c437bbcbfbe44614b39d757e9bd76be6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":380},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u16.png"}},
{
          "id":"1cb34c5c84064370a97bf3ef03a0bdfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":380},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c05c5373d94f709bfa10a970b71885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":380},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u20.png"}},
{
          "id":"f266b3e8009249959cf3a4910b2935d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":380},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ad68f2e29e64e8692816d87cc78509f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":380},
                "size":{
                  "width":140,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u22.png"}},
{
          "id":"116157ffd5934c6cb5af9bdeac8fd47c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":380},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab15f57ef6148ee9f17b4e454f974bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":380},
                "size":{
                  "width":150,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u24.png"}},
{
          "id":"b815b93ffdb743daa60937c43939faad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":430},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07d5ac466029447cae85e55a5864e3be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":430},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u16.png"}},
{
          "id":"f5fb8d50aab946cabedae52b1a9eed49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":430},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b5fa0a7dd8740a293b9ef23623753cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":430},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u16.png"}},
{
          "id":"ac2a6ffb84a14d719e9d887e392f46f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":430},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28868885625248b78e990f59d838c2b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":430},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u20.png"}},
{
          "id":"1d5bad1338c04420b5aec4cabc7889fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":430},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19dae1170b1247df97c8df93842248c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":430},
                "size":{
                  "width":140,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u22.png"}},
{
          "id":"5940a536f5704630b89acf9a5675a649",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":430},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504a14088da049e19542cae6bdd088e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":430},
                "size":{
                  "width":150,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u24.png"}},
{
          "id":"ee67c09a66ea4b3eb2afea624a4269e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":200},
            "size":{
              "width":190,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab93b09304f44a0aa9cee52811f5a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":200},
                "size":{
                  "width":190,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u56.png"}},
{
          "id":"27711667735b47ffb1e7bb3dea37ba44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":280},
            "size":{
              "width":190,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f71237dc14b5463bbd57df97413794be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":280},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u58.png"}},
{
          "id":"174f7032b74e4f0aaa566e92e62586cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":330},
            "size":{
              "width":190,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a576a715c3a4e998f02da2b727bdbce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":330},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u58.png"}},
{
          "id":"c6004e054a1042099de79abebd2464ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":380},
            "size":{
              "width":190,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa3211431fa44726845ac0c8b910076b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":380},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u58.png"}},
{
          "id":"d272ee231b584b6481457629d6de30a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":430},
            "size":{
              "width":190,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9081a9ad6842c1b72de30fe7b46ed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":430},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u58.png"}},
{
          "id":"b0682b4d633543c0abda82ef186652d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":96},
            "size":{
              "width":605,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e81dcaa8dc7409eb4037ab427f7526b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":96},
                "size":{
                  "width":605,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生成绩单查看/u66.png"}},
{
          "id":"9f1623b5f8204fd38d985166d30115f6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":102.5},
            "size":{
              "width":150,
              "height":37}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "8ba5514fa6fd4e9aa0ad3ceabccf0bc1":{
      "scriptId":"u0"},
    "774d9b713e6b4a71b308d05cd22e3695":{
      "scriptId":"u1"},
    "609a071248584b45a8abdc6f36fc2955":{
      "scriptId":"u2"},
    "51e1e223b3304b76a66908e13492a007":{
      "scriptId":"u3"},
    "2ae62487e7294aa0a0451a1f4d5dab43":{
      "scriptId":"u4"},
    "522f4c59a7c745739d49df905e268917":{
      "scriptId":"u5"},
    "0f0481e0fd484c53876f04f1bf81c13f":{
      "scriptId":"u6"},
    "2e669f49afe54cf9808a1d3233b0a8c5":{
      "scriptId":"u7"},
    "77d36a649ba44b6cab54eac13d566115":{
      "scriptId":"u8"},
    "279958309f114e80bbbe84ce8a0898bc":{
      "scriptId":"u9"},
    "c4093495d6b944b697261bbd75a43ef9":{
      "scriptId":"u10"},
    "46b60e441bcc4c499860b5c10ff057a3":{
      "scriptId":"u11"},
    "295a344eacb246a8b83a885c82b1c261":{
      "scriptId":"u12"},
    "a8d74efbfce34e6787b72d2ea004c8b1":{
      "scriptId":"u13"},
    "a00f8f3fc4a14e88863235db92833eeb":{
      "scriptId":"u14"},
    "5bfa1b5404c341e8951577cabe174f94":{
      "scriptId":"u15"},
    "1a78535d4fca461d8948b6e867e50a78":{
      "scriptId":"u16"},
    "66ee410c892e480ba9d8827f502b1385":{
      "scriptId":"u17"},
    "46d3b30a7e7c491fbf519172b1f20480":{
      "scriptId":"u18"},
    "93eabba5762241f2aad3206f9c0646db":{
      "scriptId":"u19"},
    "9551c7a87fdb460092a013e6dbab861f":{
      "scriptId":"u20"},
    "b57837c969ae42ff87e6ed00534945be":{
      "scriptId":"u21"},
    "2906de3e09654027ac55093ccf0fe065":{
      "scriptId":"u22"},
    "e9aa51ec44f64c3199d19c550f2aa1f2":{
      "scriptId":"u23"},
    "6ab73b6ff37947168204b690e3028a9f":{
      "scriptId":"u24"},
    "32556b3963a3459595556d77202ebd87":{
      "scriptId":"u25"},
    "48d38ab494e248ceae3103440aeb9546":{
      "scriptId":"u26"},
    "0a142f1722584d54a4cb5715c9b07c01":{
      "scriptId":"u27"},
    "ba9a4f9ca92d4fbc80eac41e118b17ed":{
      "scriptId":"u28"},
    "4d40d42ade3e45b8b02987fafca59ad1":{
      "scriptId":"u29"},
    "bc4e82e00c62456fa27580c8efbb783e":{
      "scriptId":"u30"},
    "686ab31f3d7043ac9cc85df0f82bde06":{
      "scriptId":"u31"},
    "dd0dda3068b5441f9382f955ca83aed2":{
      "scriptId":"u32"},
    "e30b9e3dd32042c2aa82d28f952ca4fb":{
      "scriptId":"u33"},
    "b91c0467d4a34e8ebc517db259c7a191":{
      "scriptId":"u34"},
    "be4604ee3b3746e2aa30fe46716ff589":{
      "scriptId":"u35"},
    "18a7421f3d05473781da06139f21544f":{
      "scriptId":"u36"},
    "fcc22299fe614f229837aea5ec8b3041":{
      "scriptId":"u37"},
    "0ab815427cdb4a45bbc12387f79fef3a":{
      "scriptId":"u38"},
    "c437bbcbfbe44614b39d757e9bd76be6":{
      "scriptId":"u39"},
    "1cb34c5c84064370a97bf3ef03a0bdfd":{
      "scriptId":"u40"},
    "43c05c5373d94f709bfa10a970b71885":{
      "scriptId":"u41"},
    "f266b3e8009249959cf3a4910b2935d3":{
      "scriptId":"u42"},
    "2ad68f2e29e64e8692816d87cc78509f":{
      "scriptId":"u43"},
    "116157ffd5934c6cb5af9bdeac8fd47c":{
      "scriptId":"u44"},
    "2ab15f57ef6148ee9f17b4e454f974bf":{
      "scriptId":"u45"},
    "b815b93ffdb743daa60937c43939faad":{
      "scriptId":"u46"},
    "07d5ac466029447cae85e55a5864e3be":{
      "scriptId":"u47"},
    "f5fb8d50aab946cabedae52b1a9eed49":{
      "scriptId":"u48"},
    "2b5fa0a7dd8740a293b9ef23623753cb":{
      "scriptId":"u49"},
    "ac2a6ffb84a14d719e9d887e392f46f8":{
      "scriptId":"u50"},
    "28868885625248b78e990f59d838c2b7":{
      "scriptId":"u51"},
    "1d5bad1338c04420b5aec4cabc7889fe":{
      "scriptId":"u52"},
    "19dae1170b1247df97c8df93842248c0":{
      "scriptId":"u53"},
    "5940a536f5704630b89acf9a5675a649":{
      "scriptId":"u54"},
    "504a14088da049e19542cae6bdd088e1":{
      "scriptId":"u55"},
    "ee67c09a66ea4b3eb2afea624a4269e5":{
      "scriptId":"u56"},
    "8ab93b09304f44a0aa9cee52811f5a62":{
      "scriptId":"u57"},
    "27711667735b47ffb1e7bb3dea37ba44":{
      "scriptId":"u58"},
    "f71237dc14b5463bbd57df97413794be":{
      "scriptId":"u59"},
    "174f7032b74e4f0aaa566e92e62586cd":{
      "scriptId":"u60"},
    "5a576a715c3a4e998f02da2b727bdbce":{
      "scriptId":"u61"},
    "c6004e054a1042099de79abebd2464ee":{
      "scriptId":"u62"},
    "aa3211431fa44726845ac0c8b910076b":{
      "scriptId":"u63"},
    "d272ee231b584b6481457629d6de30a3":{
      "scriptId":"u64"},
    "ff9081a9ad6842c1b72de30fe7b46ed1":{
      "scriptId":"u65"},
    "b0682b4d633543c0abda82ef186652d1":{
      "scriptId":"u66"},
    "4e81dcaa8dc7409eb4037ab427f7526b":{
      "scriptId":"u67"},
    "9f1623b5f8204fd38d985166d30115f6":{
      "scriptId":"u68"}}});