$axure.loadCurrentPage({
  "url":"教师评价.html",
  "generationDate":new Date(1526387346167.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a412471bd97441f9a1208a909ecdacaa",
    "type":"Axure:Page",
    "name":"教师评价",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"10e92bde1e2e4bb9bf60e7c54f0e56b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1424,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"749d705c31174283814c76cd74aa6df6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1424,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师评价/u0.png"}},
{
          "id":"9f961f47174e40709e4906eb57423e3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":13},
            "size":{
              "width":225,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0e3155cd9d945fc8b33d20e6cce61b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":13},
                "size":{
                  "width":225,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7ba0bb9f6d7438ba3bbc93ad8539df7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":157},
            "size":{
              "width":401,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89f45416dcb2469695d6f7df9381034f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":157},
                "size":{
                  "width":401,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"0625419796e9402ca0db0815cd8c2f21",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":212},
            "size":{
              "width":93,
              "height":23}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 出勤及课堂表现",
                      "target":{
                        "targetType":"page",
                        "url":"出勤及课堂表现.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fa0e3ad5eac1442396c565ad173726bc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":319},
            "size":{
              "width":93,
              "height":23}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人作业",
                      "target":{
                        "targetType":"page",
                        "url":"个人作业.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3b348cd166df4678b029ac84396aace3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":567},
            "size":{
              "width":93,
              "height":23}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 小组作业",
                      "target":{
                        "targetType":"page",
                        "url":"小组作业.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"39790bbb708047acba49a595e9ad4f9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1424,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d2c9d93989b4f53b718a4d9fe9610dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1424,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"527cbafb7cfa49e9bd7b1dc405849a0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":500,
              "y":15},
            "size":{
              "width":365,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20f4f265e5364a778cbbc6b0d21668d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":500,
                  "y":15},
                "size":{
                  "width":365,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c3875a11181417ba99274d52d0db9a0",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":91},
            "size":{
              "width":217,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79e5e9c86f9a43c6a89a3f6d96314af1",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":217,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd22baf4f75e435191f680842c69aa12",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":217,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ceb50fdf0514748a0cd0485e9fed322",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":217,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 教师设置评价页面",
                              "target":{
                                "targetType":"page",
                                "url":"教师设置评价页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/教师评价/u15.png"}}]}]},
{
          "id":"2ed3ef85cb3a4a9f9542a95c617b4cc5",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":603.5,
              "y":91},
            "size":{
              "width":217,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ac373d10e3d444ebfdeff0cbe1fdd02",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":217,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0cdb9921eed245c5968b7e7eca8fa3aa",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":217,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ed86412d81a42f2ba0cf443a8c597db",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":217,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师评价/u15.png"}}]}]},
{
          "id":"24be30a2cc5c40a296376944b3386b5c",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":1093,
              "y":91},
            "size":{
              "width":217,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be821e3873f342968240e30e867e0fbf",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":217,
                  "height":28}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49c13afb5a104a61a7aaa550aed7e3b9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":217,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c67ab66520294ad9a153022de238fb82",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":217,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师评价/u15.png"}}]}]},
{
          "id":"d2d56aa2c7d94c88a05d44b287814388",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1093,
              "y":174},
            "size":{
              "width":217,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16532539e2b9443db4502cd32ea9ffce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1093,
                  "y":174},
                "size":{
                  "width":217,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生成绩单查看",
                      "target":{
                        "targetType":"page",
                        "url":"学生成绩单查看.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教师评价/u25.png"}},
{
          "id":"94e51e0e77ca41be9fd6ab47c21e6290",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1093,
              "y":264},
            "size":{
              "width":217,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4394582c4b6c4f6288483db29559313c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1093,
                  "y":264},
                "size":{
                  "width":217,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生成绩学生自评部分",
                      "target":{
                        "targetType":"page",
                        "url":"学生成绩学生自评部分.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教师评价/u25.png"}},
{
          "id":"7b4cedd29d864072b7ff832bfca86a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1093,
              "y":364},
            "size":{
              "width":217,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f11390c338c74eb097de1580d4806006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1093,
                  "y":364},
                "size":{
                  "width":217,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生成绩小组互评部分",
                      "target":{
                        "targetType":"page",
                        "url":"学生成绩小组互评部分.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教师评价/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "10e92bde1e2e4bb9bf60e7c54f0e56b2":{
      "scriptId":"u0"},
    "749d705c31174283814c76cd74aa6df6":{
      "scriptId":"u1"},
    "9f961f47174e40709e4906eb57423e3f":{
      "scriptId":"u2"},
    "f0e3155cd9d945fc8b33d20e6cce61b4":{
      "scriptId":"u3"},
    "a7ba0bb9f6d7438ba3bbc93ad8539df7":{
      "scriptId":"u4"},
    "89f45416dcb2469695d6f7df9381034f":{
      "scriptId":"u5"},
    "0625419796e9402ca0db0815cd8c2f21":{
      "scriptId":"u6"},
    "fa0e3ad5eac1442396c565ad173726bc":{
      "scriptId":"u7"},
    "3b348cd166df4678b029ac84396aace3":{
      "scriptId":"u8"},
    "39790bbb708047acba49a595e9ad4f9a":{
      "scriptId":"u9"},
    "6d2c9d93989b4f53b718a4d9fe9610dc":{
      "scriptId":"u10"},
    "527cbafb7cfa49e9bd7b1dc405849a0b":{
      "scriptId":"u11"},
    "20f4f265e5364a778cbbc6b0d21668d4":{
      "scriptId":"u12"},
    "6c3875a11181417ba99274d52d0db9a0":{
      "scriptId":"u13"},
    "79e5e9c86f9a43c6a89a3f6d96314af1":{
      "scriptId":"u14"},
    "dd22baf4f75e435191f680842c69aa12":{
      "scriptId":"u15"},
    "2ceb50fdf0514748a0cd0485e9fed322":{
      "scriptId":"u16"},
    "2ed3ef85cb3a4a9f9542a95c617b4cc5":{
      "scriptId":"u17"},
    "1ac373d10e3d444ebfdeff0cbe1fdd02":{
      "scriptId":"u18"},
    "0cdb9921eed245c5968b7e7eca8fa3aa":{
      "scriptId":"u19"},
    "6ed86412d81a42f2ba0cf443a8c597db":{
      "scriptId":"u20"},
    "24be30a2cc5c40a296376944b3386b5c":{
      "scriptId":"u21"},
    "be821e3873f342968240e30e867e0fbf":{
      "scriptId":"u22"},
    "49c13afb5a104a61a7aaa550aed7e3b9":{
      "scriptId":"u23"},
    "c67ab66520294ad9a153022de238fb82":{
      "scriptId":"u24"},
    "d2d56aa2c7d94c88a05d44b287814388":{
      "scriptId":"u25"},
    "16532539e2b9443db4502cd32ea9ffce":{
      "scriptId":"u26"},
    "94e51e0e77ca41be9fd6ab47c21e6290":{
      "scriptId":"u27"},
    "4394582c4b6c4f6288483db29559313c":{
      "scriptId":"u28"},
    "7b4cedd29d864072b7ff832bfca86a8b":{
      "scriptId":"u29"},
    "f11390c338c74eb097de1580d4806006":{
      "scriptId":"u30"}}});