$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1526387345789.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7629a38fe23547cf925eacde4e014cf5",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"83c3765637db407ba9915ef89980c818",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1424,
              "height":880},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4df27b3b207c4420ab7f55cab3f32090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1424,
                  "height":880},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"91eeb0b29d864834b48a2eb33059aaed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1424,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be4905f74f648d5bfec3b9f2bc5a75c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1424,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"9312b209cd2a4f1d9440ab4671e6b2dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":570,
              "y":15},
            "size":{
              "width":197,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"491b431a2b7e482e8ebfc8a13a0f15cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":15},
                "size":{
                  "width":197,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b75d91bfe054a03832feb347bc8ff27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":113.5},
            "size":{
              "width":436,
              "height":631}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a321a2301de34e20bd917dd8c49b6f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":113.5},
                "size":{
                  "width":436,
                  "height":631}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"6ff750096836473e995840abdc9cb68e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":810,
              "y":184},
            "size":{
              "width":480,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b1ec9f5559a47c9b3fb9c4a173a6e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":810,
                  "y":184},
                "size":{
                  "width":480,
                  "height":470},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"a55a47c4ab794578a494b30cc8d920a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Black', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"900",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":810,
              "y":184},
            "size":{
              "width":480,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95117b4c5678458386bcadb5d1a563e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"900",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":810,
                  "y":184},
                "size":{
                  "width":480,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"fb9042d5e24b4b6d8c19442779ac9e1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":324},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf0535829d1b47ea9f38c1520aa7adad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":324},
                "size":{
                  "width":90,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"eb981367ae2d42d298b5cd32d8c09fb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":404},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4974b98ee13445e8834bfb67aa6034fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":404},
                "size":{
                  "width":90,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"a4d9e882f938487cb029cf815919f907",
          "label":"用户名输入",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":324},
            "size":{
              "width":240,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"bcfb532937b544c28fe35b653509ad9a",
          "label":"密码输入",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":404},
            "size":{
              "width":240,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"16e8696777e14d32a3a5ea563d46b1cd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":514},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"c08e94c28437405f87a8e5048e4213bc",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":1083,
              "y":514},
            "size":{
              "width":107,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c71a6aed18244d4b0fdbad792209107",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":107,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9807c320ed95427d876aec63c5220cb9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF3F3F3},
                    "size":{
                      "width":107,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc78c0c661b74eab8e2c950b84e42a33",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF3F3F3},
                        "size":{
                          "width":107,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u21.png"}}]},
{
              "id":"355b30cfea864c4ba57809b00efede38",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":107,
                  "height":40},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0413969c1b5d4392b3dca6ae22c1f7d6",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":107,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74ab8ead26164ca096ab353d2d18a1d1",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF3F3F3},
                        "size":{
                          "width":107,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"54ddcf6a21ed4a2ea48cb5d4106dca47",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF3F3F3},
                            "size":{
                              "width":107,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 教师评价",
                                  "target":{
                                    "targetType":"page",
                                    "url":"教师评价.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/home/u25.png"}},
{
                      "id":"0ca890e9000844faa91d08712f93360a",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF3F3F3},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":107,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"da319ba99c10411bb63ea54216dd19a6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF3F3F3},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":107,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"linkWindow",
                                  "description":"在 当前窗口 打开 学生",
                                  "target":{
                                    "targetType":"page",
                                    "url":"学生.html",
                                    "includeVariables":true},
                                  "linkType":"current"}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/home/u27.png"}}]}],
              "parentCellId":"9807c320ed95427d876aec63c5220cb9"}]}]}},
  "masters":{
},
  "objectPaths":{
    "83c3765637db407ba9915ef89980c818":{
      "scriptId":"u0"},
    "4df27b3b207c4420ab7f55cab3f32090":{
      "scriptId":"u1"},
    "91eeb0b29d864834b48a2eb33059aaed":{
      "scriptId":"u2"},
    "5be4905f74f648d5bfec3b9f2bc5a75c":{
      "scriptId":"u3"},
    "9312b209cd2a4f1d9440ab4671e6b2dd":{
      "scriptId":"u4"},
    "491b431a2b7e482e8ebfc8a13a0f15cb":{
      "scriptId":"u5"},
    "9b75d91bfe054a03832feb347bc8ff27":{
      "scriptId":"u6"},
    "a321a2301de34e20bd917dd8c49b6f4c":{
      "scriptId":"u7"},
    "6ff750096836473e995840abdc9cb68e":{
      "scriptId":"u8"},
    "3b1ec9f5559a47c9b3fb9c4a173a6e19":{
      "scriptId":"u9"},
    "a55a47c4ab794578a494b30cc8d920a1":{
      "scriptId":"u10"},
    "95117b4c5678458386bcadb5d1a563e8":{
      "scriptId":"u11"},
    "fb9042d5e24b4b6d8c19442779ac9e1a":{
      "scriptId":"u12"},
    "bf0535829d1b47ea9f38c1520aa7adad":{
      "scriptId":"u13"},
    "eb981367ae2d42d298b5cd32d8c09fb3":{
      "scriptId":"u14"},
    "4974b98ee13445e8834bfb67aa6034fd":{
      "scriptId":"u15"},
    "a4d9e882f938487cb029cf815919f907":{
      "scriptId":"u16"},
    "bcfb532937b544c28fe35b653509ad9a":{
      "scriptId":"u17"},
    "16e8696777e14d32a3a5ea563d46b1cd":{
      "scriptId":"u18"},
    "c08e94c28437405f87a8e5048e4213bc":{
      "scriptId":"u19"},
    "7c71a6aed18244d4b0fdbad792209107":{
      "scriptId":"u20"},
    "9807c320ed95427d876aec63c5220cb9":{
      "scriptId":"u21"},
    "cc78c0c661b74eab8e2c950b84e42a33":{
      "scriptId":"u22"},
    "355b30cfea864c4ba57809b00efede38":{
      "scriptId":"u23"},
    "0413969c1b5d4392b3dca6ae22c1f7d6":{
      "scriptId":"u24"},
    "74ab8ead26164ca096ab353d2d18a1d1":{
      "scriptId":"u25"},
    "54ddcf6a21ed4a2ea48cb5d4106dca47":{
      "scriptId":"u26"},
    "0ca890e9000844faa91d08712f93360a":{
      "scriptId":"u27"},
    "da319ba99c10411bb63ea54216dd19a6":{
      "scriptId":"u28"}}});