$axure.loadCurrentPage({
  "url":"教师设置评价页面.html",
  "generationDate":new Date(1526387353518.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e939f4400e6543a9b4067abda417dd66",
    "type":"Axure:Page",
    "name":"教师设置评价页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9842a4966e464f638ff1ae77a0471f90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":180},
            "size":{
              "width":850,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e349cf3fb8d245dcbb6358d551513a84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":180},
                "size":{
                  "width":850,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师设置评价页面/u0.png"}},
{
          "id":"ea63ee1795ee49088ab06b560d8a45d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1424,
              "height":1590},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f57a7dc884f8445598281b3aa24912dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1424,
                  "height":1590},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师设置评价页面/u2.png"}},
{
          "id":"e5aa9dab799e4c8cad3377d592313e8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1424,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"478d636babce48999d0835260e5448bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1424,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"1112cb78468446b4b026097cd74c06f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":491,
              "y":15},
            "size":{
              "width":421,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"894f21f4c34d403a902d2e0cca941a2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":491,
                  "y":15},
                "size":{
                  "width":421,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4683ef0396d24574bb61cd5688e24c20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":102},
            "size":{
              "width":143,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83280d7d21fa4dd18656cffd62dc9509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":102},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师设置评价页面/u8.png"}},
{
          "id":"55f439ddc4224c8192d35779c5e56e91",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":102},
            "size":{
              "width":720,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"501e05b1a9ac4091b4011c10375b49c0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1220,
              "y":1125},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教师评价",
                      "target":{
                        "targetType":"page",
                        "url":"教师评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a6673729005443b49ac29247b050f6b9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":1125},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教师评价",
                      "target":{
                        "targetType":"page",
                        "url":"教师评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"67e4c74fcdf2493082dd6a77c454c6ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":800},
            "size":{
              "width":830,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5cb356e9d824c359131bad49ece3d52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":800},
                "size":{
                  "width":830,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教师设置评价页面/u13.png"}},
{
          "id":"45423a23778f4f8b861f8ae8f93cac40",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":170},
            "size":{
              "width":143,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a2f6dbbeb94b3ea174403963137678",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72262b5479704d828f34afc156a548ae",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85194cb9845445138d3ddae0d6089cf6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":143,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u17.png"}}]},
{
              "id":"cf5c6d6bef9a4447ae6f53f4eb327e1b",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":143,
                  "height":40},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4061f67f0c0342d89324214b1817512a",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":143,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9cdd7031ff004529a950de26b7118e98",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":143,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5fb3f5b01c24464198d87e0e7ec97593",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":143,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 2",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setPanelState",
                                  "description":"设置 评价表设置 到 新创建评价表",
                                  "panelsToStates":[{
                                      "panelPath":["386c7b857f474d6ab7d5d59c3cd4ae80"],
                                      "stateInfo":{
                                        "setStateType":"diagram",
                                        "stateNumber":2,
                                        "stateValue":{
                                          "exprType":"stringLiteral",
                                          "value":"1",
                                          "stos":[]},
                                        "loop":false,
                                        "showWhenSet":false,
                                        "options":{
                                          "compress":false}}}]}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/教师设置评价页面/u21.png"}},
{
                      "id":"35582fde215f48f69d740e1b0cec0f57",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":143,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"febb1e646865409f991a73c647af4289",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":143,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"fadeWidget",
                                  "description":"显示 评价表设置,<br>(Image)",
                                  "objectsToFades":[{
                                      "objectPath":["386c7b857f474d6ab7d5d59c3cd4ae80"],
                                      "fadeInfo":{
                                        "fadeType":"show",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["9a667441ba504f32b4388ed255590637"],
                                      "fadeInfo":{
                                        "fadeType":"show",
                                        "options":{
                                          "showType":"none"}}}]}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/教师设置评价页面/u23.png"}}]}],
              "parentCellId":"72262b5479704d828f34afc156a548ae"}]},
{
          "id":"386c7b857f474d6ab7d5d59c3cd4ae80",
          "label":"评价表设置",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":180},
            "size":{
              "width":830,
              "height":590}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c656483455c44c82b97a939ce67dc4b1",
              "label":"原有评价表",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9a667441ba504f32b4388ed255590637",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":230,
                      "y":0},
                    "size":{
                      "width":400,
                      "height":589},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2e2e66fb6384f41a6ad98334e1c22e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":230,
                          "y":0},
                        "size":{
                          "width":400,
                          "height":589},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u6.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0761d0c9540e473299e17d8ada35ecf6",
              "label":"新创建评价表",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"72ff94628d764025bf70c1f7811e3af1",
                  "label":"一级指标",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"028b55dbdf9c4c99b791f1b2a8b0f27e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/一级指标_u28.png"}},
{
                  "id":"99686d1aaf14495ab9e64e3afe4ff7a5",
                  "label":"二级指标",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":178,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c31bd3d0fd0d4bf180fa87da09a6d9c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":178,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/一级指标_u28.png"}},
{
                  "id":"ed9b6fe0fbb8464787dba4d2fced0468",
                  "label":"三级指标",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":359,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69c59a3bccb34e64a74f3d84bd66efe0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":359,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/一级指标_u28.png"}},
{
                  "id":"e184d6b03fd54af28988e333af969c3f",
                  "label":"观测点",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":0},
                    "size":{
                      "width":290,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b5d838ceb13407c890d28e88b5e4350",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":540,
                          "y":0},
                        "size":{
                          "width":290,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/观测点_u34.png"}},
{
                  "id":"5b6dd3ace3624c4d8b7f93fa9708f300",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":180}},
                  "adaptiveStyles":{
}},
{
                  "id":"318d84ccd5134df1aa01927a9ee1a3db",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":178,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"292e25b88f9641d0bdcb7c2615528fb3",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":178,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":60}},
                  "adaptiveStyles":{
}},
{
                  "id":"c4a5f907b6bb4153be637d14323fe36b",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":178,
                      "y":120},
                    "size":{
                      "width":130,
                      "height":90}},
                  "adaptiveStyles":{
}},
{
                  "id":"fde361d364c84fd4a272f458d99c299f",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":359,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"14531c5acc10443d8fb8600edb058441",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":359,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"e717e2633156429887239ef110b1d587",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":359,
                      "y":90},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"dde4d1e91773402eb5eaff963236cd66",
                  "label":"比例1",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":0},
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"382fec25e26b49739fa8279932ca4d38",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":130,
                          "y":0},
                        "size":{
                          "width":50,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/比例1_u43.png"}},
{
                  "id":"7ebb600d25a34f7295383020e3d5efb1",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":30},
                    "size":{
                      "width":50,
                      "height":180}},
                  "adaptiveStyles":{
}},
{
                  "id":"2f68e861ace449bcaeab4a423e171d3f",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":359,
                      "y":120},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"a22aff34e3e141d896382023dc79f49c",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":359,
                      "y":150},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"74cdc36821ef40ccbe09e3ec39f4bdd5",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":359,
                      "y":180},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"8e7ee16acfce48e6afe9fac5db53ac29",
                  "label":"比例2",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":308,
                      "y":0},
                    "size":{
                      "width":52,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe77cd6e1aa647e095aff577af2a4c36",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":308,
                          "y":0},
                        "size":{
                          "width":52,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/比例2_u49.png"}},
{
                  "id":"daa21db4ad2d4bbda11405798893d187",
                  "label":"比例3",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":487,
                      "y":0},
                    "size":{
                      "width":53,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce3e0b8349a742d2806875f6b06704c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":487,
                          "y":0},
                        "size":{
                          "width":53,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/比例3_u51.png"}},
{
                  "id":"abca16f120ef4ee48505fc1269d8e0c8",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":308,
                      "y":30},
                    "size":{
                      "width":52,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"e960f93b690f4ab6bcf131615b0fdee1",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":308,
                      "y":60},
                    "size":{
                      "width":52,
                      "height":60}},
                  "adaptiveStyles":{
}},
{
                  "id":"df258afae5e9404aba738f1a2e917d5c",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":308,
                      "y":120},
                    "size":{
                      "width":52,
                      "height":90}},
                  "adaptiveStyles":{
}},
{
                  "id":"a40987b37a4b4e028390093472ce3cdb",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":489,
                      "y":30},
                    "size":{
                      "width":51,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"68112c72464a4c4a9886725da5559785",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":489,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"72d57e2276704312b836f63cc5a3a435",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":489,
                      "y":90},
                    "size":{
                      "width":51,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"080356a40ff34a879a3d11f9d4c01c12",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":489,
                      "y":120},
                    "size":{
                      "width":51,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"8e430c63f2804a909527edb73e4e9b8e",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":489,
                      "y":150},
                    "size":{
                      "width":51,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"2962ad41ef6f4ac2b9c966a2ac2ad909",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":30},
                    "size":{
                      "width":290,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"0a92af8fb18b4d3799af42b2cd97ec64",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":60},
                    "size":{
                      "width":290,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"e054fe1672f14de19229e8d51b7b8a1f",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":90},
                    "size":{
                      "width":290,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"7afc8b2e2ccc4fffaf659c66994e49c0",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":120},
                    "size":{
                      "width":290,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"2de6febad3d540d9a3a506caaa753626",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":150},
                    "size":{
                      "width":290,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"4f6c6eda1f9d4c74a6e4e06f5b6b4b2c",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":180},
                    "size":{
                      "width":290,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"353ee75f7a5848f792ca0b23d07f091e",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":489,
                      "y":180},
                    "size":{
                      "width":51,
                      "height":30}},
                  "adaptiveStyles":{
}},
{
                  "id":"a7ad6d00d6b94b9abe8666b60b92c56e",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Black', 'Arial'",
                    "fontWeight":"900",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCC3300,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 一级指标+",
                              "objectsToFades":[{
                                  "objectPath":["9be62a04bb8f4e00ab477c507b568e4b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"14668d3d04974e638a60b2625ea3e54a",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Black', 'Arial'",
                    "fontWeight":"900",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCC3300,
                      "opacity":1},
                    "location":{
                      "x":278,
                      "y":0},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 二级指标+",
                              "objectsToFades":[{
                                  "objectPath":["e385953a162244a78110c8dc8cc9a3ea"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"f1e597655603433b95a8685e07c42632",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Black', 'Arial'",
                    "fontWeight":"900",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCC3300,
                      "opacity":1},
                    "location":{
                      "x":457,
                      "y":0},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 三级指标+",
                              "objectsToFades":[{
                                  "objectPath":["af4b43e0740a4e6181ca2e5bab15a7a8"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"3cd39573714441c6b3500d45f4aaa3b8",
                  "label":"",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Black', 'Arial'",
                    "fontWeight":"900",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCC3300,
                      "opacity":1},
                    "location":{
                      "x":800,
                      "y":0},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 观测点+",
                              "objectsToFades":[{
                                  "objectPath":["cb4319a72543445782533045372a4e4a"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"e385953a162244a78110c8dc8cc9a3ea",
                  "label":"二级指标+",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":178,
                      "y":210},
                    "size":{
                      "width":130,
                      "height":25},
                    "visible":false},
                  "adaptiveStyles":{
}},
{
                  "id":"af4b43e0740a4e6181ca2e5bab15a7a8",
                  "label":"三级指标+",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":359,
                      "y":210},
                    "size":{
                      "width":130,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
}},
{
                  "id":"cb4319a72543445782533045372a4e4a",
                  "label":"观测点+",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":540,
                      "y":210},
                    "size":{
                      "width":290,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
}},
{
                  "id":"9be62a04bb8f4e00ab477c507b568e4b",
                  "label":"一级指标+",
                  "parentDynamicPanel":"386c7b857f474d6ab7d5d59c3cd4ae80",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":210},
                    "size":{
                      "width":130,
                      "height":130},
                    "visible":false},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"cbd20720dc6843838ab72e20b4f8a0bb",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":800},
            "size":{
              "width":143,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e50a636119324c5fb6c3671d67ec7236",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"901c3b01901549d2b9fc604703d79736",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b80c343218fe4232b1a017d7e1f78415",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":143,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u17.png"}}]},
{
              "id":"57c7177a08544d7eb925564c701e2d61",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":143,
                  "height":40},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7625fe0bced453e92a3dfdb70924f53",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":143,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ace0561ec55746639608ef85e4f6f7b2",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":143,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f40a64e5c312414ea86882ed9a8d6385",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":143,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/教师设置评价页面/u21.png"}},
{
                      "id":"9534c0bd40684e11b06fc91040cf6363",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":143,
                          "height":20},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"45bb7412c73b44f78cae1c8ce484c759",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":20},
                            "size":{
                              "width":143,
                              "height":20},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setPanelState",
                                  "description":"设置 学生名单设置 到 已有名单",
                                  "panelsToStates":[{
                                      "panelPath":["e761ee45da6e47d9aae1ae2a4d78fbc6"],
                                      "stateInfo":{
                                        "setStateType":"diagram",
                                        "stateNumber":1,
                                        "stateValue":{
                                          "exprType":"stringLiteral",
                                          "value":"1",
                                          "stos":[]},
                                        "loop":false,
                                        "showWhenSet":false,
                                        "options":{
                                          "compress":false}}}]}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/教师设置评价页面/u23.png"}}]}],
              "parentCellId":"901c3b01901549d2b9fc604703d79736"}]},
{
          "id":"e761ee45da6e47d9aae1ae2a4d78fbc6",
          "label":"学生名单设置",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":800},
            "size":{
              "width":830,
              "height":280}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"3a0b669340da4a7ebab3110655f1bc0b",
              "label":"已有名单",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9a569de3b4ff431597babc3851abcc79",
                  "label":"",
                  "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":80,
                      "y":20},
                    "size":{
                      "width":310,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c985fc79bb84217adf68c5f969eb7b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":80,
                          "y":20},
                        "size":{
                          "width":310,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u87.png"}},
{
                  "id":"25dac212b7f7467eb473f6810b613c26",
                  "label":"",
                  "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":390,
                      "y":20},
                    "size":{
                      "width":280,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f6322e69537454c9df90486abf5e0c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":390,
                          "y":20},
                        "size":{
                          "width":280,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u89.png"}},
{
                  "id":"18430ea38f584dc6935d694676d24cc9",
                  "label":"",
                  "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":80,
                      "y":50},
                    "size":{
                      "width":310,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb8c3914049d4d67813194b09820b1fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":80,
                          "y":50},
                        "size":{
                          "width":310,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u87.png"}},
{
                  "id":"d2191658d14d4a6895421d019ec2129a",
                  "label":"",
                  "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":390,
                      "y":50},
                    "size":{
                      "width":280,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5df6205499ea4f7985bf87a162265cad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":390,
                          "y":50},
                        "size":{
                          "width":280,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u89.png"}},
{
                  "id":"1c040cd20aee47728eac17a7e756f7be",
                  "label":"",
                  "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":80,
                      "y":80},
                    "size":{
                      "width":310,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19b0b73381a94943a859feb0b9009487",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":80,
                          "y":80},
                        "size":{
                          "width":310,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u87.png"}},
{
                  "id":"5ae05b53574b48edba7fdb2306154216",
                  "label":"",
                  "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":390,
                      "y":80},
                    "size":{
                      "width":280,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"778325850dde417fb204e38072b2963b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":390,
                          "y":80},
                        "size":{
                          "width":280,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u89.png"}},
{
                  "id":"6d874fe104f5482f93a358db5b6442bf",
                  "label":"",
                  "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":80,
                      "y":110},
                    "size":{
                      "width":310,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0768f03046c14fb282e99c3e3b2ae0b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":80,
                          "y":110},
                        "size":{
                          "width":310,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u87.png"}},
{
                  "id":"0a3c9b61eb724b1ea6307ddc88aede89",
                  "label":"",
                  "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":390,
                      "y":110},
                    "size":{
                      "width":280,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"573fc664c5584ec09ba048bc17b2abc9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e761ee45da6e47d9aae1ae2a4d78fbc6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":390,
                          "y":110},
                        "size":{
                          "width":280,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/教师设置评价页面/u89.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "9842a4966e464f638ff1ae77a0471f90":{
      "scriptId":"u0"},
    "e349cf3fb8d245dcbb6358d551513a84":{
      "scriptId":"u1"},
    "ea63ee1795ee49088ab06b560d8a45d6":{
      "scriptId":"u2"},
    "f57a7dc884f8445598281b3aa24912dd":{
      "scriptId":"u3"},
    "e5aa9dab799e4c8cad3377d592313e8c":{
      "scriptId":"u4"},
    "478d636babce48999d0835260e5448bd":{
      "scriptId":"u5"},
    "1112cb78468446b4b026097cd74c06f5":{
      "scriptId":"u6"},
    "894f21f4c34d403a902d2e0cca941a2e":{
      "scriptId":"u7"},
    "4683ef0396d24574bb61cd5688e24c20":{
      "scriptId":"u8"},
    "83280d7d21fa4dd18656cffd62dc9509":{
      "scriptId":"u9"},
    "55f439ddc4224c8192d35779c5e56e91":{
      "scriptId":"u10"},
    "501e05b1a9ac4091b4011c10375b49c0":{
      "scriptId":"u11"},
    "a6673729005443b49ac29247b050f6b9":{
      "scriptId":"u12"},
    "67e4c74fcdf2493082dd6a77c454c6ab":{
      "scriptId":"u13"},
    "e5cb356e9d824c359131bad49ece3d52":{
      "scriptId":"u14"},
    "45423a23778f4f8b861f8ae8f93cac40":{
      "scriptId":"u15"},
    "d5a2f6dbbeb94b3ea174403963137678":{
      "scriptId":"u16"},
    "72262b5479704d828f34afc156a548ae":{
      "scriptId":"u17"},
    "85194cb9845445138d3ddae0d6089cf6":{
      "scriptId":"u18"},
    "cf5c6d6bef9a4447ae6f53f4eb327e1b":{
      "scriptId":"u19"},
    "4061f67f0c0342d89324214b1817512a":{
      "scriptId":"u20"},
    "9cdd7031ff004529a950de26b7118e98":{
      "scriptId":"u21"},
    "5fb3f5b01c24464198d87e0e7ec97593":{
      "scriptId":"u22"},
    "35582fde215f48f69d740e1b0cec0f57":{
      "scriptId":"u23"},
    "febb1e646865409f991a73c647af4289":{
      "scriptId":"u24"},
    "386c7b857f474d6ab7d5d59c3cd4ae80":{
      "scriptId":"u25"},
    "9a667441ba504f32b4388ed255590637":{
      "scriptId":"u26"},
    "a2e2e66fb6384f41a6ad98334e1c22e6":{
      "scriptId":"u27"},
    "72ff94628d764025bf70c1f7811e3af1":{
      "scriptId":"u28"},
    "028b55dbdf9c4c99b791f1b2a8b0f27e":{
      "scriptId":"u29"},
    "99686d1aaf14495ab9e64e3afe4ff7a5":{
      "scriptId":"u30"},
    "c31bd3d0fd0d4bf180fa87da09a6d9c9":{
      "scriptId":"u31"},
    "ed9b6fe0fbb8464787dba4d2fced0468":{
      "scriptId":"u32"},
    "69c59a3bccb34e64a74f3d84bd66efe0":{
      "scriptId":"u33"},
    "e184d6b03fd54af28988e333af969c3f":{
      "scriptId":"u34"},
    "7b5d838ceb13407c890d28e88b5e4350":{
      "scriptId":"u35"},
    "5b6dd3ace3624c4d8b7f93fa9708f300":{
      "scriptId":"u36"},
    "318d84ccd5134df1aa01927a9ee1a3db":{
      "scriptId":"u37"},
    "292e25b88f9641d0bdcb7c2615528fb3":{
      "scriptId":"u38"},
    "c4a5f907b6bb4153be637d14323fe36b":{
      "scriptId":"u39"},
    "fde361d364c84fd4a272f458d99c299f":{
      "scriptId":"u40"},
    "14531c5acc10443d8fb8600edb058441":{
      "scriptId":"u41"},
    "e717e2633156429887239ef110b1d587":{
      "scriptId":"u42"},
    "dde4d1e91773402eb5eaff963236cd66":{
      "scriptId":"u43"},
    "382fec25e26b49739fa8279932ca4d38":{
      "scriptId":"u44"},
    "7ebb600d25a34f7295383020e3d5efb1":{
      "scriptId":"u45"},
    "2f68e861ace449bcaeab4a423e171d3f":{
      "scriptId":"u46"},
    "a22aff34e3e141d896382023dc79f49c":{
      "scriptId":"u47"},
    "74cdc36821ef40ccbe09e3ec39f4bdd5":{
      "scriptId":"u48"},
    "8e7ee16acfce48e6afe9fac5db53ac29":{
      "scriptId":"u49"},
    "fe77cd6e1aa647e095aff577af2a4c36":{
      "scriptId":"u50"},
    "daa21db4ad2d4bbda11405798893d187":{
      "scriptId":"u51"},
    "ce3e0b8349a742d2806875f6b06704c0":{
      "scriptId":"u52"},
    "abca16f120ef4ee48505fc1269d8e0c8":{
      "scriptId":"u53"},
    "e960f93b690f4ab6bcf131615b0fdee1":{
      "scriptId":"u54"},
    "df258afae5e9404aba738f1a2e917d5c":{
      "scriptId":"u55"},
    "a40987b37a4b4e028390093472ce3cdb":{
      "scriptId":"u56"},
    "68112c72464a4c4a9886725da5559785":{
      "scriptId":"u57"},
    "72d57e2276704312b836f63cc5a3a435":{
      "scriptId":"u58"},
    "080356a40ff34a879a3d11f9d4c01c12":{
      "scriptId":"u59"},
    "8e430c63f2804a909527edb73e4e9b8e":{
      "scriptId":"u60"},
    "2962ad41ef6f4ac2b9c966a2ac2ad909":{
      "scriptId":"u61"},
    "0a92af8fb18b4d3799af42b2cd97ec64":{
      "scriptId":"u62"},
    "e054fe1672f14de19229e8d51b7b8a1f":{
      "scriptId":"u63"},
    "7afc8b2e2ccc4fffaf659c66994e49c0":{
      "scriptId":"u64"},
    "2de6febad3d540d9a3a506caaa753626":{
      "scriptId":"u65"},
    "4f6c6eda1f9d4c74a6e4e06f5b6b4b2c":{
      "scriptId":"u66"},
    "353ee75f7a5848f792ca0b23d07f091e":{
      "scriptId":"u67"},
    "a7ad6d00d6b94b9abe8666b60b92c56e":{
      "scriptId":"u68"},
    "14668d3d04974e638a60b2625ea3e54a":{
      "scriptId":"u69"},
    "f1e597655603433b95a8685e07c42632":{
      "scriptId":"u70"},
    "3cd39573714441c6b3500d45f4aaa3b8":{
      "scriptId":"u71"},
    "e385953a162244a78110c8dc8cc9a3ea":{
      "scriptId":"u72"},
    "af4b43e0740a4e6181ca2e5bab15a7a8":{
      "scriptId":"u73"},
    "cb4319a72543445782533045372a4e4a":{
      "scriptId":"u74"},
    "9be62a04bb8f4e00ab477c507b568e4b":{
      "scriptId":"u75"},
    "cbd20720dc6843838ab72e20b4f8a0bb":{
      "scriptId":"u76"},
    "e50a636119324c5fb6c3671d67ec7236":{
      "scriptId":"u77"},
    "901c3b01901549d2b9fc604703d79736":{
      "scriptId":"u78"},
    "b80c343218fe4232b1a017d7e1f78415":{
      "scriptId":"u79"},
    "57c7177a08544d7eb925564c701e2d61":{
      "scriptId":"u80"},
    "d7625fe0bced453e92a3dfdb70924f53":{
      "scriptId":"u81"},
    "ace0561ec55746639608ef85e4f6f7b2":{
      "scriptId":"u82"},
    "f40a64e5c312414ea86882ed9a8d6385":{
      "scriptId":"u83"},
    "9534c0bd40684e11b06fc91040cf6363":{
      "scriptId":"u84"},
    "45bb7412c73b44f78cae1c8ce484c759":{
      "scriptId":"u85"},
    "e761ee45da6e47d9aae1ae2a4d78fbc6":{
      "scriptId":"u86"},
    "9a569de3b4ff431597babc3851abcc79":{
      "scriptId":"u87"},
    "2c985fc79bb84217adf68c5f969eb7b7":{
      "scriptId":"u88"},
    "25dac212b7f7467eb473f6810b613c26":{
      "scriptId":"u89"},
    "3f6322e69537454c9df90486abf5e0c5":{
      "scriptId":"u90"},
    "18430ea38f584dc6935d694676d24cc9":{
      "scriptId":"u91"},
    "fb8c3914049d4d67813194b09820b1fe":{
      "scriptId":"u92"},
    "d2191658d14d4a6895421d019ec2129a":{
      "scriptId":"u93"},
    "5df6205499ea4f7985bf87a162265cad":{
      "scriptId":"u94"},
    "1c040cd20aee47728eac17a7e756f7be":{
      "scriptId":"u95"},
    "19b0b73381a94943a859feb0b9009487":{
      "scriptId":"u96"},
    "5ae05b53574b48edba7fdb2306154216":{
      "scriptId":"u97"},
    "778325850dde417fb204e38072b2963b":{
      "scriptId":"u98"},
    "6d874fe104f5482f93a358db5b6442bf":{
      "scriptId":"u99"},
    "0768f03046c14fb282e99c3e3b2ae0b3":{
      "scriptId":"u100"},
    "0a3c9b61eb724b1ea6307ddc88aede89":{
      "scriptId":"u101"},
    "573fc664c5584ec09ba048bc17b2abc9":{
      "scriptId":"u102"}}});